### ISSUE TITLE
ARAM crashes latest build outright.

### ISSUE THREAD

**Issue by sudravirodhin** [pipe01/legendary-rune-maker#12]
[dump_20181211053106.mdmp.zip](https://github.com/pipe01/legendary-rune-maker/files/2666097/dump_20181211053106.mdmp.zip)
[dump_20181211053138.mdmp.zip](https://github.com/pipe01/legendary-rune-maker/files/2666098/dump_20181211053138.mdmp.zip)
Two dumps for good measure.

**Comment by pipe01** [comment]
Should be fixed with d58c65f but I'm going to wait until I test it to close this. Thanks for reporting!
