### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by Rakuryo** [pipe01/legendary-rune-maker#14]
http://prntscr.com/m0p8wi

Happens everytime i start the app.
Here is the dump.
[dump_20181228173904.mdmp.zip](https://github.com/pipe01/legendary-rune-maker/files/2715355/dump_20181228173904.mdmp.zip)

**Comment by pipe01** [comment]
Hi, thanks for reporting the issue. Can you check if this works? [LRM.zip](https://github.com/pipe01/legendary-rune-maker/files/2715371/LRM.zip)

**Comment by Rakuryo** [comment]
Hey, thanks for the quick response! Just started a game with it. Seems to work!

**Comment by pipe01** [comment]
Glad to hear! I'll close this, but let me know if you have any other issues.
