### ISSUE TITLE
Various crashes and invalid runes

### ISSUE THREAD

**Issue by xPazz** [pipe01/legendary-rune-maker#16]
It generates runes but some of the keys are missing. LRM crashes often and sometimes even crashes the main league game. I will update this post with crash logs as soon as it happens again.

**Comment by xPazz** [comment]
https://paz.pw/fb90a5ca0ab0ae0b417375db154e26dc.png

**Comment by pipe01** [comment]
Can you try deleting the `cache` folder? It's in the same dir as the application `.exe`.

**Comment by xPazz** [comment]
I've cleared the cache and so far it's working fine. You should try adding some detection that the cache is corrupted or out of date, and clear it..

**Comment by pipe01** [comment]
It should actually renew when there's a new LoL version, maybe that's not
enough.

**Comment by pipe01** [comment]
Well, if it crashes again let me know!

**Comment by xPazz** [comment]
runes issue on jax resurfaced

**Comment by pipe01** [comment]
I can't seem to reproduce

**Comment by pipe01** [comment]
It shouldn't upload invalid runes anymore, hopefully the crashes have been solved too.
