### ISSUE TITLE
Crashes on start up

### ISSUE THREAD

**Issue by fernando1sg** [pipe01/legendary-rune-maker#19]
[dump_20190123233143.mdmp.zip](https://github.com/pipe01/legendary-rune-maker/files/2789595/dump_20190123233143.mdmp.zip)

Gracias por crear este software si no fuera por esto no volveria a jugar lol porque es molesto cambiar runas todo el tiempo.

**Comment by pipe01** [comment]
De nada! Prueba con [esto](https://ci.appveyor.com/api/buildjobs/kqrbmbtdd8kculxi/artifacts/Legendary%20Rune%20Maker%2Fbin%2FDebug%20build.zip).

**Comment by fernando1sg** [comment]
Gracias por responder tan pronto, en cuanto cambie los archivos mi antivirus avast detecto algo raro y creo en un archivo como un virus tal vez un falso positivo, pero tan pronto desactive el antivirus y con los archivos nuevos funcionó.

**Comment by pipe01** [comment]
Me alegro de que funcionase! Lo del antivirus es probablemente porque no esta firmado el .exe, lo arreglaría si no fuese tan caro jajaja

**Comment by pipe01** [comment]
Hay una en el readme, muchísimas gracias!
