### ISSUE TITLE
[Question] Rune pages

### ISSUE THREAD

**Issue by wooles** [pipe01/legendary-rune-maker#20]
Can you make it to override existing rune page rather than creating a new one?

**Comment by pipe01** [comment]
It should overwrite the currently selected page in the client.

**Comment by wooles** [comment]
In my case it creates new page every time, even for the same champion. 
![hnplbj9 1](https://user-images.githubusercontent.com/9068595/51705555-36148b80-201c-11e9-9a93-b775532f106c.png)

**Comment by pipe01** [comment]
> Also, it might be a bug, but sometimes some runes are not selected, I have to pick it manually.

Can you provide more detail on this? It's been happening for a few users but I can't seem to reproduce.

**Comment by wooles** [comment]
It can also be a visual bug (tbh I didn't check that if i leave it unselected it will pick proper runes) but sometimes I can see exclamation mark next to a rune page and when i open it some runes are not selected. But as is said i experienced it before even without your tool so it migh be riot's fault. I will make a screenshot for you next time i see it.

**Comment by pipe01** [comment]
I would appreciate that.

**Comment by wooles** [comment]
As I promised I made a video with a bug for you.
https://streamable.com/y2hd2

**Comment by pipe01** [comment]
Do you know what rune should have been there by any chance? That's really helpful anyways.

**Comment by wooles** [comment]
u.gg which is provider selected showing this setup 
![zufd3o8 1](https://user-images.githubusercontent.com/9068595/51752573-1d59b380-20b8-11e9-9166-7f7a9fe86727.png)

**Comment by pipe01** [comment]
That same page works fine for me. Try deleting the `cache` folder, it's alongside the app .exe
