### ISSUE TITLE
[Suggestion] Stop accepting game when you press decline

### ISSUE THREAD

**Issue by derdossi** [pipe01/legendary-rune-maker#23]
Hi , I have been using your app for about a month now and i have an issue. I play in Diamond 4 to Diamond 2 right now and sometimes you get a really bad teamcomp or some trolls or not your ideal role and people leave. Then normally the queue pops immediately with the same morons as before and because of the app even if I decline the game it still somehow accepts it. It would be nice if it does not accept the game anymore if you pressed decline. Another idea would be to add a Decline button in the popup that appears when the queue pops. 
Thanks Dossi

**Comment by pipe01** [comment]
It should in fact be doing that already, but I have seen that it fails.
I'll see what I can do!

**Comment by pipe01** [comment]
Should be working!
