### ISSUE TITLE
cant select role when in blind pick

### ISSUE THREAD

**Issue by xPazz** [pipe01/legendary-rune-maker#24]
It'll just return to fill.

**Comment by pipe01** [comment]
You can uncheck the "Attach" check box in order to stop the position and champion from updating.

**Comment by pipe01** [comment]
I realized I forgot a line that allowed this to happen, fixing it

**Comment by xPazz** [comment]
alright thanks, you should probably make an FAQ with some of this stuff

**Comment by pipe01** [comment]
Yeah i think i'm going to do that
