### ISSUE TITLE
still crashing on 450fd8b 

### ISSUE THREAD

**Issue by xPazz** [pipe01/legendary-rune-maker#28]
[dump_20190208122419.mdmp.zip](https://github.com/pipe01/legendary-rune-maker/files/2845071/dump_20190208122419.mdmp.zip)

**Comment by xPazz** [comment]
@pipe01

**Comment by pipe01** [comment]
Sorry, I've been busy and haven't been able to investigate, hopefully I'll have some time soon. In the meantime, have you tried a fresh installation?

**Comment by pipe01** [comment]
Can you try the latest build?

**Comment by xPazz** [comment]
[dump_20190212091136.mdmp.zip](https://github.com/pipe01/legendary-rune-maker/files/2854932/dump_20190212091136.mdmp.zip)

**Comment by pipe01** [comment]
It seems like I didn't properly commit, can you try now? It should print the locale, which apparently is giving problems.

**Comment by xPazz** [comment]
[dump_20190212171124.mdmp.zip](https://github.com/pipe01/legendary-rune-maker/files/2856816/dump_20190212171124.mdmp.zip)

**Comment by pipe01** [comment]
Should be fixed!
