### ISSUE TITLE
more crash yes

### ISSUE THREAD

**Issue by xPazz** [pipe01/legendary-rune-maker#30]
[dump_20190223023702.mdmp.zip](https://github.com/pipe01/legendary-rune-maker/files/2896397/dump_20190223023702.mdmp.zip)
[dump_20190223023630.mdmp.zip](https://github.com/pipe01/legendary-rune-maker/files/2896398/dump_20190223023630.mdmp.zip)

**Comment by xPazz** [comment]
[dump_20190302142226.mdmp.zip](https://github.com/pipe01/legendary-rune-maker/files/2922658/dump_20190302142226.mdmp.zip)
different crash issue i think ^^

**Comment by pipe01** [comment]
The second one has been fixed, the first two ones seem to be rare U.GG errors to which I can't really find a cause to. Make sure to report them if they ever happen again.
