### ISSUE TITLE
crashes on new minor patch

### ISSUE THREAD

**Issue by xPazz** [pipe01/legendary-rune-maker#36]
[dump_20190410112932.mdmp.zip](https://github.com/pipe01/legendary-rune-maker/files/3068800/dump_20190410112932.mdmp.zip)
[dump_20190410112909.mdmp.zip](https://github.com/pipe01/legendary-rune-maker/files/3068801/dump_20190410112909.mdmp.zip)

the item lists arent injected, but runes are

**Comment by pipe01** [comment]
Both of those are related to the U.GG provider, which I just fixed.
