### ISSUE TITLE
8.23 Rune Updates

### ISSUE THREAD

**Issue by sudravirodhin** [pipe01/legendary-rune-maker#4]
Runes got updated with 8.23.
I see commits to fix the runes but there's no release to download and it doesn't see an update.

Even if you don't allow downloading runes automatically I'd still love the basic rune-picking feature to work again since it's so much faster than the UI and it saves it in a catalog that rivals or surpasses Runebook's.

Thanks!

If you have a Ko-Fi or Paypal link for donations let me know.
This is quality software and I'm mad at myself for being unable to compile it without bugging you.

**Comment by pipe01** [comment]
I was waiting to release it in case there was an issue with the changes, but I'll release it as soon as I can (hopefully tomorrow). Automatic rune downloading will be a top priority, I think that's one of the main features of the program.

As for donating, I do have a PayPal but I feel like you should spend your money somewhere else, but I appreciate that you would be willing to. If you do want to, I could send you a link via email.

**Comment by sudravirodhin** [comment]
Thank you! I was trying to pry the dev build out of AppVeyor myself for
like the whole day today but eventually realized I couldn't.

**Comment by pipe01** [comment]
Yeah the only way to get files out of the build is through artifacts AFAIK

**Comment by sudravirodhin** [comment]
I'll keep up-to-date on the debug versions and keep you in the loop so I can help polish this for the next release. Only bug that comes to mind from pre 8.23 was the position but that thought bottom was support and vice versa. Not sure if it's still the case in latest build, will try auto-picker again tonight and shoot you logs in the other issue.

Thanks again Felipe!

**Comment by pipe01** [comment]
I'm not sure how the position confusion could happen, so definitely let me know if it happens again!
