### ISSUE TITLE
Crash when trying to parse very large spellId ints.

### ISSUE THREAD

**Issue by diogotr7** [pipe01/legendary-rune-maker#40]
The crash can be fixed by changing the variable type from int to string so it can be deserialized properly.

**Comment by pipe01** [comment]
When does this happen? Do you have a crash dump?

**Comment by diogotr7** [comment]
This happens every champ select for me. I was able to reproduce it by creating a custom game, filling every slot with a bot, starting champ select and then running the application. It then crashes immediately.

Upon further inspection, the changes i made were in LCU.NET, not this program. Should i make a new issue there?

**Comment by pipe01** [comment]
That'd be great

**Comment by diogotr7** [comment]
Posted here: https://github.com/pipe01/LCU.NET/issues/1
