### ISSUE TITLE
Pick Summoners 1.1.0-debug

### ISSUE THREAD

**Issue by sudravirodhin** [pipe01/legendary-rune-maker#5]
Auto-pick summoners uses the fill options regardless of role locked in. Happens every time. Reproducible.

**Comment by pipe01** [comment]
All auto picking needs some work

**Comment by pipe01** [comment]
Can you send a screenshot of your automation config?

**Comment by sudravirodhin** [comment]
Yes, contents of a specific file or the actual choices in the GUI?

**Comment by pipe01** [comment]
Just the GUI will do it.

**Comment by sudravirodhin** [comment]
Happened again just now:
![image](https://user-images.githubusercontent.com/3495530/49197017-20e3ef00-f342-11e8-9c65-4f146096e6c3.png)

**Comment by pipe01** [comment]
Can you download the latest build and try again? I added some logging so
that should give me some insight. The log file should be in the logs folder
next to the executable.

**Comment by sudravirodhin** [comment]
Absolutely. Will update you when I next use it.

**Comment by sudravirodhin** [comment]
[logs.zip](https://github.com/pipe01/legendary-rune-maker/files/2630025/logs.zip)
Here are my logs from last night. Not sure if it captured it happening or not.

Will try and deliberately catch it tonight.

**Comment by pipe01** [comment]
I can see that at some point flash and heal were picked, but I'm unsure if the config was or wasn't properly set then. I added config logging so that should clear things up for next time.

**Comment by sudravirodhin** [comment]
You got it. I'll use the newest build when I play today.

**Comment by pipe01** [comment]
I think I'm going to rewrite a lot of code, it's gotten very buggy and
complex.

**Comment by sudravirodhin** [comment]
So ARAM and Co-op games are considered "FILL" then?

As for the bot/sup switch, sometimes it picks the wrong summoners but based on your feedback this might be fixed.

**Comment by pipe01** [comment]
> So ARAM and Co-op games are considered "FILL" then?

Yup

> As for the bot/sup switch, sometimes it picks the wrong summoners but based on your feedback this might be fixed.

🤞

**Comment by pipe01** [comment]
I feel like I'm ready to release the next version, so give it a try and tell me if you find any more bugs.

Also, do you have a Discord?

**Comment by sudravirodhin** [comment]
Will try it tonight and update you if I find anything. Thanks!

Yes I do have Discord. Sudravirodhin#5048.

**Comment by sudravirodhin** [comment]
Yikes, getting a run-time exception and I can't even dump. Fresh extract of the latest build.

Screenshot: 
![image](https://user-images.githubusercontent.com/3495530/49322064-adb4b700-f4c0-11e8-8719-2feddd58539a.png)

**Comment by sudravirodhin** [comment]
Last working build with fresh start was: 4a9fd8d7

Will see if it's a config file problem by overwriting latest debug on top.

**Comment by sudravirodhin** [comment]
Crashes out with latest commit 606a6be unzipped on top of 4a9fd8d.

Logs here:
[logs.zip](https://github.com/pipe01/legendary-rune-maker/files/2635423/logs.zip)

**Comment by sudravirodhin** [comment]
Seems it has to do with the LoginDetector function because when not logged in or without client open it crashes. At least you know where to look now!

**Comment by sudravirodhin** [comment]
Aha! Remember you asked when that bot/supp switch happens? Look!

![image](https://user-images.githubusercontent.com/3495530/49324671-74437200-f4e7-11e8-978f-ccc1a262e734.png)

**Comment by pipe01** [comment]
Do you have the logs? Especially for the support-adc swapping.

**Comment by pipe01** [comment]
About the summoner spells, if you choose a spell that isn't available it should just not do anything, isn't that what happened there?

**Comment by pipe01** [comment]
K I found the cause for the swapping bug, turns out the images were out of order in the UI lol

**Comment by sudravirodhin** [comment]
> About the summoner spells, if you choose a spell that isn't available it should just not do anything, isn't that what happened there?

If I chose a spell that wasn't available it freaked out and gave me Clarity and Exhaust.

Here are the logs from last night's sessions.
[logs.zip](https://github.com/pipe01/legendary-rune-maker/files/2636120/logs.zip)
