### ISSUE TITLE
Incomplete files

### ISSUE THREAD

**Issue by nicolay4ever** [pipe01/legendary-rune-maker#52]
i already import sln file and loading all files so much failed to restore and incomplete files , I am using 2019 version

**Comment by Chobocharles** [comment]
This is an old issue, but I'm pretty confident this has been fixed. I ran into a few items like the EXE missing, the system not recognizing some git commands, and not having the solution's targeted framework installed. 

For anyone else that's running into these issues, the resolution for myself was to ensure the Legendary Rune Maker was the startup project, install the latest version of git from https://git-scm.com/, and installing the appropriate framework from https://dotnet.microsoft.com/download/dotnet-framework 

After these items are addressed, cleaning and building will work.

**Comment by Chobocharles** [comment]
@pipe01, @dragitz, or @rincew1nd - I believe this can be closed.

**Comment by pipe01** [comment]
Yeah it works fine for me
