### ISSUE TITLE
Champion.GG item set provider is broken

### ISSUE THREAD

**Issue by pedropinto0** [pipe01/legendary-rune-maker#54]
[dump_20210222012019.mdmp.zip](https://github.com/pipe01/legendary-rune-maker/files/6018753/dump_20210222012019.mdmp.zip)

w10 pro version: 20H2

**Comment by pipe01** [comment]
Some providers are bugged, you're better off using U.GG for everything right now

**Comment by pedropinto0** [comment]
thanks for the quick answer my man, have a great sunday

**Comment by pipe01** [comment]
You too 😄
