### ISSUE TITLE
Black Screen on Client

### ISSUE THREAD

**Issue by Firefoxin** [pipe01/legendary-rune-maker#9]
every option works correctly but when game start the black screen appear. [[Image](http://xup.ir/images/33868947123361875876.png)]
Game Mode: Summoners Rift **Blind **Pick****

**Comment by pipe01** [comment]
That's weird. Can you check if it works on other game modes?

**Comment by sudravirodhin** [comment]
This has happened to me too at random. Requires a restart of the app. Not sure of cause yet.

**Comment by Firefoxin** [comment]
test all mode, didn't happened anymore :)

**Comment by pipe01** [comment]
Glad to hear!
